package chess.chessgame;

/**
 * This class represents data returned by {@link ChessGame}.
 * 
 * @author Andraz
 */
public class ChessGameResults {

    /**
     * PGN generated by {@link ChessGame}
     */
    private String              pgn;

    /**
     * Statistics for {@link ChessGame}
     */
    private ChessGameStatistics statistics;


    /**
     * Constructor
     * 
     * @param pgn
     *            PGN generated by {@link ChessGame}
     * @param gameStatistics
     *            statistics created by {@link ChessGame}
     */
    public ChessGameResults(String pgn, ChessGameStatistics gameStatistics) {
        this.pgn = pgn;
        this.statistics = gameStatistics;
    }


    /**
     * Gets PGN generated by {@link ChessGame}
     */
    public String getPgn() {
        return this.pgn;
    }


    /**
     * Gets statistics for {@link ChessGame}
     */
    public ChessGameStatistics getStatistics() {
        return this.statistics;
    }

}
